//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Üretimtakip
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblFirmaCari
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblFirmaCari()
        {
            this.TblSatinalmaTeklif = new HashSet<TblSatinalmaTeklif>();
        }
    
        public int ID { get; set; }
        public string Unvan { get; set; }
        public string Adres { get; set; }
        public string YetkiliKisi { get; set; }
        public string Telefon { get; set; }
        public string VergiDairesi { get; set; }
        public string VergiKimlikNo { get; set; }
        public Nullable<bool> Durum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSatinalmaTeklif> TblSatinalmaTeklif { get; set; }
    }
}
