//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Üretimtakip
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMalzemeGenelFiyat
    {
        public int ID { get; set; }
        public string Malzeme { get; set; }
        public string Birim { get; set; }
        public string DövizCinsi { get; set; }
        public string BirimFiyat { get; set; }
        public string SonGuncelleme { get; set; }
    }
}
