//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Üretimtakip
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMalzeme
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblMalzeme()
        {
            this.TblUrunRecetesi = new HashSet<TblUrunRecetesi>();
        }
    
        public int ID { get; set; }
        public Nullable<int> AnaKategori { get; set; }
        public Nullable<int> AltKategori { get; set; }
        public string Malzemeler { get; set; }
        public string Aciklama { get; set; }
        public string Görsel { get; set; }
        public Nullable<System.DateTime> SonGuncellenme { get; set; }
    
        public virtual TblSubKategori TblSubKategori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblUrunRecetesi> TblUrunRecetesi { get; set; }
        public virtual TblBabaKategori TblBabaKategori { get; set; }
    }
}
