//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Üretimtakip
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSatinalmaTeklif
    {
        public int ID { get; set; }
        public Nullable<int> TeklifNo { get; set; }
        public Nullable<System.DateTime> TeklifTarihi { get; set; }
        public Nullable<System.DateTime> GecerlilikTarihi { get; set; }
        public Nullable<int> FirmaID { get; set; }
        public Nullable<int> OnayVerenAdID { get; set; }
        public string Malzeme { get; set; }
        public Nullable<int> Adet { get; set; }
        public Nullable<decimal> BirimFiyat { get; set; }
        public string Parabirimi { get; set; }
        public Nullable<byte> Durum { get; set; }
    
        public virtual TblFirmaCari TblFirmaCari { get; set; }
        public virtual TblPersonel TblPersonel { get; set; }
    }
}
