//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Üretimtakip
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblUrunRecetesi
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<int> Olusturan { get; set; }
        public Nullable<int> Onaylayan { get; set; }
        public Nullable<short> MaliyetHesabi { get; set; }
        public string TedarikciFirma { get; set; }
        public Nullable<int> AnaKategori { get; set; }
        public Nullable<int> AltKategori { get; set; }
        public Nullable<int> Malzeme { get; set; }
        public string Aciklama { get; set; }
        public string BirimFiyat { get; set; }
        public string ParaBirimi { get; set; }
        public string Birim { get; set; }
        public string Miktar { get; set; }
        public Nullable<decimal> ToplamTutar { get; set; }
    
        public virtual TblMalzeme TblMalzeme { get; set; }
        public virtual TblPersonel TblPersonel { get; set; }
        public virtual TblPersonel TblPersonel1 { get; set; }
    }
}
